org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Java/jdk-26.0.1

# Fabric properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.13

# Mod properties
mod_version=0.8.2
maven_group=com.viperproxy
archives_base_name=viperproxy

# Dependencies
fabric_api_version=0.153.0+26.2
